#!/bin/bash

# kill all processes
pids=`ps -e | awk '{ if(!($4=="bash"||$4=="CMD")) {print $1} }'`

for p in $pids; do
    kill -9 $p
done

# delete all temporary files
TMPPATH="$HOME/../usr/tmp"
rm -rf $TMPPATH/* $TMPPATH/.*

# start vnc server
vncserver -listen tcp :1
DISPLAY=:1 xhost +
